# Vendored bytes are somebody else's: the two faces and their licence, and the scripts
# `scripts/vendored.toml` records with the licence beside each. No hook here may rewrite one, because
# a newline appended to a script is a digest `tests/test_vendored.py` then refuses, which is how the
# first vendored htmx came to differ from every published build by one byte. The size guard steps
# aside for the same files rather than raising its limit: a face is a megabyte for the coverage the
# stylesheet explains and the diagram library is three and a half, loaded only when a drawing is
# asked for, and a large file anywhere else in this repository is still an accident.
exclude: ^src/mainplate/assets/.*(\.woff2|\.min\.js|-LICENSE\.txt|-OFL\.txt)$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.38.0
    hooks:
      - id: check-github-workflows
      - id: check-github-actions

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.29.0
    hooks:
      - id: zizmor

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.2
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.3
    hooks:
      - id: uv-lock
