"""
The reference files beside the bundled skills, derived from the source they describe.

A bundled skill is read by a model working on somebody else's repository, which cannot see this one,
so whatever it needs to know about the console has to be in the skill's own directory. A limit, a
protocol or an example restated there by hand is a copy that drifts the moment the source moves and
fails nothing when it does. So every such fact is written by this script into a `generated/`
directory beside the skill that needs it, and the pre-commit hook runs this on every commit, which
fails the commit whenever a file here changes. **Each `generated/` directory is this script's
entirely**: a file in one that `generated()` does not name is deleted.

`generated()` is pure and the whole of what is derived; `main` is the shell that writes it. A
literal in a module too slow to import (`console.py` takes seconds, because it reaches every
provider SDK) or in a file that is not a module (a bundled plugin is a script) is read with `ast`
rather than imported, which is why the hook can run on every commit rather than on a list of paths
that would itself have to be kept in step with this table.

The cost, stated: the package carries copies of a few scripts and design notes, and a hand-written
`SKILL.md` can still contradict a generated file beside it. Each `SKILL.md` says the generated file
wins, and the facts a `SKILL.md` states itself are the ones that do not move.
"""

from __future__ import annotations

import ast
import json
import re
import stat
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import timedelta
from pathlib import Path
from typing import Annotated
from typing import Final
from typing import Union

from pydantic import Field
from pydantic import TypeAdapter
from pydantic.json_schema import JsonSchemaMode

from mainplate import artifacts
from mainplate import context
from mainplate.plugins import installed
from mainplate.plugins import protocol
from mainplate.plugins import running

ROOT: Final = Path(__file__).resolve().parent.parent
SOURCE: Final = ROOT / "src" / "mainplate"
SKILLS: Final = SOURCE / "bundled-context" / "skills"

# The directory under a skill that this script owns, and the only kind it writes into.
GENERATED: Final = "generated"

# Every payload a plugin can be sent, in the order the protocol lists its events, so the schema of
# what a plugin receives is one union it can be checked against.
PAYLOADS: Final = (
    protocol.SettingUp,
    protocol.Calling,
    protocol.Gating,
    protocol.Requesting,
    protocol.Stopping,
    protocol.Ending,
    protocol.Composing,
    protocol.Acting,
)


@dataclass(frozen=True, slots=True)
class Written:
    """
    One generated file: where under `SKILLS` it goes, every byte of it, and whether it runs.

    `executable` because a script held up as an example is copied by a model as it is, and a copy of
    a plugin or a job that the console then cannot execute is an example that teaches the wrong
    thing. It is the source's own bit, carried by `copied`, rather than a column somebody keeps.
    """

    path: Path
    text: str
    executable: bool = False

    @classmethod
    def copied(cls, path: Path, source: Path) -> Written:
        """
        A file as it is, since an example a model is told to copy is worth most unedited.

        No header, unlike a note: a script's first line is its interpreter.
        """
        return cls(path=path, text=source.read_text(encoding="utf-8"), executable=is_executable(source))


def is_executable(path: Path) -> bool:
    """Whether the file's owner may run it, which is the one bit of a mode git records."""
    return bool(path.stat().st_mode & stat.S_IXUSR)


def relative(path: Path) -> str:
    """A source's path as a reader of the repository would write it."""
    return path.relative_to(ROOT).as_posix()


def headed(text: str, *sources: Path) -> str:
    """Markdown that says where it came from, so an editor who opens it knows to edit that instead."""
    named = " and ".join(relative(source) for source in sources)
    return f"<!-- Generated by scripts/skills.py from {named}. Edit that, not this. -->\n\n{text.strip()}\n"


def literal(path: Path, name: str) -> object:
    """
    A module-level literal, read without importing the file it is in.

    For a module that is slow to import and for a script that is not a module at all. Anything other
    than a literal there raises, which is the loud failure wanted when somebody computes the value.
    """
    for node in ast.parse(path.read_text(encoding="utf-8")).body:
        match node:
            case ast.Assign(targets=[ast.Name(id=found)], value=value) if found == name:
                return ast.literal_eval(value)
            case ast.AnnAssign(target=ast.Name(id=found), value=ast.expr() as value) if found == name:
                return ast.literal_eval(value)
            case _:
                pass
    raise LookupError(f"{relative(path)} assigns no literal {name}")


def section(path: Path, heading: str) -> str:
    """One section of a Markdown document, from its heading to the next heading as high or higher."""
    lines = path.read_text(encoding="utf-8").splitlines()
    start = lines.index(heading)
    level = len(heading) - len(heading.lstrip("#"))
    fenced = False
    taken = [heading]
    for line in lines[start + 1 :]:
        if line.startswith("```"):
            fenced = not fenced
        depth = len(line) - len(line.lstrip("#"))
        if not fenced and 0 < depth <= level and line[depth : depth + 1] == " ":
            break
        taken.append(line)
    return "\n".join(taken)


def summarised(schema: object) -> object:
    """
    A schema with each description cut to its first paragraph.

    The descriptions are the protocol's docstrings, whose first paragraph says what a thing is and
    whose rest argues for it to whoever maintains the console; a plugin's author needs the first.
    """
    match schema:
        case dict():
            return {
                key: value.split("\n\n", 1)[0].replace("\n", " ")
                if key == "description" and isinstance(value, str)
                else summarised(value)
                for key, value in schema.items()
            }
        case list():
            return [summarised(each) for each in schema]
        case _:
            return schema


def schema_of[T](adapter: TypeAdapter[T], comment: str, mode: JsonSchemaMode) -> str:
    """
    A JSON Schema as a file, with what it is for in `$comment`, which every validator ignores.

    `by_alias` because the wire names are the aliases: `return` and `set`, where the fields are
    `returned` and `setting`. What a plugin receives is drawn in serialization mode and what it
    answers in validation mode, since those are the two directions the console reads them in, and
    both by `protocol.SpokenSchema`, which draws what `spoken` actually sends and leaves validation
    as Pydantic draws it.
    """
    drawn = adapter.json_schema(by_alias=True, mode=mode, schema_generator=protocol.SpokenSchema)
    return json.dumps(summarised({"$comment": comment, **drawn}), indent=2) + "\n"


def worded(span: timedelta) -> str:
    """
    A timeout as the sentence around it reads it: whole minutes where it is some, else seconds.

    Whole seconds only, since every timeout it words is set in minutes or seconds; a fraction would
    be truncated rather than printed, and `test_skills.py` holds the singular.
    """
    minutes, seconds = divmod(int(span.total_seconds()), 60)
    if seconds or not minutes:
        return f"{int(span.total_seconds())} seconds"
    return "1 minute" if minutes == 1 else f"{minutes} minutes"


def artifact_limits() -> str:
    """
    What `file_to_artifact` accepts and the policy every version is served under.

    The policy is read out of `console.py` with `literal` rather than imported, since that module
    reaches every provider SDK; split on `;` so a reader sees one directive per line.
    """
    policy = literal(SOURCE / "console.py", "ARTIFACT_POLICY")
    if not isinstance(policy, bytes):
        raise TypeError(f"ARTIFACT_POLICY is a header's bytes, not {policy!r}")
    directives = "\n".join(each.strip() for each in policy.decode().split(";"))
    openings = ", ".join(f"`{each.decode()}`" for each in artifacts.OPENINGS)
    return headed(
        f"""
# What the store keeps, and how a version is served

`file_to_artifact` keeps a file that is UTF-8, at most {artifacts.LARGEST:,} bytes
({artifacts.LARGEST / 1024 / 1024:g} MiB), and opens with one of {openings}, in any case.

Every version is served with this `Content-Security-Policy`, one directive per line:

```text
{directives}
```
""",
        SOURCE / "artifacts.py",
        SOURCE / "console.py",
    )


def guidance_limits() -> str:
    """
    Which file names count as guidance, what a skill or command may be called, and how large one is.

    The names are the bundled guidance plugin's, read with `literal` because a plugin is a script and
    not a module, so what a skill says is what that plugin actually looks for.
    """
    names = literal(SOURCE / "plugins" / "bundled" / "guidance", "GUIDANCE_NAMES")
    if not isinstance(names, tuple):
        raise TypeError(f"GUIDANCE_NAMES is a tuple of file names, not {names!r}")
    return headed(
        f"""
# Names and limits

- A directory's guidance is the first of these it tracks: {", ".join(f"`{each}`" for each in names)}.
- A skill's or a command's name is its directory, and the whole name matches
  `{whole(context.NAME)}`.
- A `SKILL.md` or `COMMAND.md` is at most {context.MAX_BODY:,} bytes, and so is what a manual
  invocation sends, the person's own words included.
""",
        SOURCE / "plugins" / "bundled" / "guidance",
        SOURCE / "context.py",
    )


def plugin_limits() -> str:
    """
    Where a plugin is declared, what it may be called, how long it has, and which effects each event allows.

    The table is drawn from `protocol.ALLOWED` rather than written out, since it is the one fact here
    a plugin's author is most likely to get wrong and the protocol is most likely to move.
    """
    effects = sorted({effect for allowed in protocol.ALLOWED.values() for effect in allowed})
    rows = "\n".join(
        f"| `{event}` | " + " | ".join("yes" if effect in protocol.ALLOWED[event] else "" for effect in effects) + " |"
        for event in protocol.EVENTS
    )
    return headed(
        f"""
# Names, limits, and which effects each event may ask for

- A repository declares its plugins in `{installed.REPOSITORY_FILE.as_posix()}`, as `plugins:`, a
  mapping from a name to a path relative to the checkout root. Nothing else is accepted there.
- A plugin's whole name matches `{whole(installed.NAMED)}`.
- A tool a repository's plugin declares reaches the model as
  `{installed.TOOL_PREFIX}<plugin>_<tool>`, and a composer answer as
  `<plugin>{installed.LEADER_SEPARATOR}<leader>`.
- `setup` is answered within {worded(running.SETTING_UP)}, and every other event within
  {worded(running.PATIENCE)}, or the plugin is stopped and the call fails.
- At `setup`, `KEY=value` lines appended to the file `${running.ENV_FILE_NAMED}` names become the
  environment of the session's commands and jobs.

`setup` is answered with what `describes.schema.json` allows. Every other event is answered with
what `answers.schema.json` allows, and only with the effects this table marks for that event:

| Event | {" | ".join(f"`{effect}`" for effect in effects)} |
|---|{"---|" * len(effects)}
{rows}
""",
        SOURCE / "plugins" / "installed.py",
        SOURCE / "plugins" / "protocol.py",
        SOURCE / "plugins" / "running.py",
    )


def generated() -> tuple[Written, ...]:
    """Every file this script owns, in full."""
    receives = TypeAdapter[object](Annotated[Union[PAYLOADS], Field(discriminator="event")])  # noqa: UP007
    return (
        Written(Path("artifact", GENERATED, "limits.md"), artifact_limits()),
        Written(Path("guidance", GENERATED, "limits.md"), guidance_limits()),
        Written(Path("guidance", GENERATED, "guidance.md"), note(ROOT / "docs" / "plugins" / "guidance.md")),
        Written(
            Path("guidance", GENERATED, "context-loading.md"), note(ROOT / "docs" / "design" / "context-loading.md")
        ),
        Written(Path("plugin", GENERATED, "limits.md"), plugin_limits()),
        Written(
            Path("plugin", GENERATED, "environment.md"),
            headed(
                section(ROOT / "docs" / "design" / "plugins.md", "### What is in the environment"),
                ROOT / "docs" / "design" / "plugins.md",
            ),
        ),
        Written(
            Path("plugin", GENERATED, "receives.schema.json"),
            schema_of(receives, "What a plugin reads on stdin, one object per run.", "serialization"),
        ),
        Written(
            Path("plugin", GENERATED, "describes.schema.json"),
            schema_of(protocol.DESCRIBED, "What a plugin prints in answer to setup.", "validation"),
        ),
        Written(
            Path("plugin", GENERATED, "answers.schema.json"),
            schema_of(protocol.ANSWERED, "What a plugin prints in answer to any event but setup.", "validation"),
        ),
        Written.copied(Path("plugin", GENERATED, "handoff"), SOURCE / "plugins" / "bundled" / "handoff"),
        Written.copied(Path("setup", GENERATED, "setup"), ROOT / ".mainplate" / "setup"),
        Written.copied(Path("setup", GENERATED, "mainplate.yaml"), ROOT / ".mainplate" / "mainplate.yaml"),
        Written.copied(Path("serve", GENERATED, "demo"), ROOT / ".mainplate" / "demo"),
    )


def note(path: Path) -> str:
    """
    A design note as it is, under the header saying where it came from.

    Its links are relative to the documentation site and lead nowhere from a skill's directory; the
    text is what a reader came for.
    """
    return headed(path.read_text(encoding="utf-8"), path)


def whole(pattern: re.Pattern[str]) -> str:
    """A pattern as somebody reads it, without the anchor that makes `fullmatch` redundant in code."""
    return pattern.pattern.removesuffix(r"\Z")


def stale(written: Mapping[Path, Written], present: tuple[Path, ...]) -> tuple[Path, ...]:
    """What is in a `generated/` directory that this script no longer writes."""
    return tuple(path for path in present if path not in written)


def main() -> int:
    """
    Bring every `generated/` directory up to date, and exit 1 if that changed anything.

    The exit is what fails the hook. pre-commit also fails a hook that modifies a tracked file, but a
    generated file nobody has added yet is not tracked, and a stale one would pass.
    """
    written = {each.path: each for each in generated()}
    present = tuple(path.relative_to(SKILLS) for path in SKILLS.glob(f"*/{GENERATED}/**/*") if path.is_file())
    changed = False
    for path in stale(written, present):
        (SKILLS / path).unlink()
        print(f"removed {path}")
        changed = True
    for path, each in written.items():
        target = SKILLS / path
        if (
            target.exists()
            and target.read_text(encoding="utf-8") == each.text
            and is_executable(target) == each.executable
        ):
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(each.text, encoding="utf-8")
        mode = target.stat().st_mode
        target.chmod(mode | 0o111 if each.executable else mode & ~0o111)
        print(f"wrote {path}")
        changed = True
    return 1 if changed else 0


if __name__ == "__main__":
    raise SystemExit(main())
